# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20170328_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
